describe('Criar anúncios', () => {
    it('successfully loads', () => {
        cy.visit('/')
        // Login
        cy.get('#IndexPageComponent > div.row.mt-2 > div > a').contains('Adote Já!').click()
        cy.wait(900)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(1) > input').click().should('be.visible').type('lipe')
        cy.wait(900)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(2) > input').click().should('be.visible').type('123')
        cy.wait(900)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > button').contains('Entrar').click()
 
        //Criar
        cy.wait(2000)
        cy.get('#navbarTogglerDemo02 > ul > a:nth-child(5)').contains('Criar Anúncio').click()
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(1) > input').click().should('be.visible').type('Box')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(2) > input').click().should('be.visible').type('Cachorro')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(3) > input').click().should('be.visible').type('Spitz')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(4) > input').click().should('be.visible').type('2')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(5) > input').click().should('be.visible').type('Macho')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(6) > input').click().should('be.visible').type('Tranquilo')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(7) > input').click().should('be.visible').type('Cachorro para adoção em Campos do Jordão')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(8) > textarea').click().should('be.visible').type('Descrição do anúncio, para fins de teste')        
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(9) > input').click().should('be.visible').type('https://www.petlove.com.br/images/breeds/193057/profile/original/spitz_alemao-p.jpg?1532539555')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(10) > input').click().should('be.visible').type('lipe')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > button').contains('Cadastrar Anúncio').click()
        cy.wait(3000)
        cy.get('#IndexPageComponent > div.container-fluid.container-cards > div > div:nth-child(4) > div > div > a').click()
        })
    })