describe('Editar anúncios', () => {
    it('successfully loads', () => {
        cy.visit('/')
        // Login
        cy.get('#IndexPageComponent > div.row.mt-2 > div > a').contains('Adote Já!').click()
        cy.wait(900)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(1) > input').click().should('be.visible').type('lipe')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(2) > input').click().should('be.visible').type('123')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > button').contains('Entrar').click()

        //Editando
        cy.wait(1000)
        cy.get('#IndexPageComponent > div.container-fluid.container-cards > div > div:nth-child(4) > div > div > a > button').click()
        cy.wait(2000)
        cy.get('#IndexPageComponent > div > div > div > div.card.mb-3 > div > div > div > a:nth-child(2) > button').click()
        //Editando campos
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(1) > input').click().clear().type('Box Da Cunha')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(2) > input').click().clear().type('Cachorro')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(3) > input').click().clear().type('Spitz')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(4) > input').click().clear().type('2')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(5) > input').click().clear().type('Macho')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(6) > input').click().clear().type('Tranquilo')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(7) > input').click().clear().type('Cachorro para adoção em Campos do Jordão. Agora editada')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(8) > textarea').click().clear().type('Descrição do anúncio, para fins de teste. Agora editada')        
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(9) > input').click().clear().type('https://www.petlove.com.br/images/breeds/193057/profile/original/spitz_alemao-p.jpg?1532539555')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > div:nth-child(10) > input').click().clear().type('lipe')
        cy.wait(300)
        cy.get('#IndexPageComponent > div.row.d-flex.justify-content-center.mt-4.mb-5 > div > div > div > form > button').contains('Editar Anúncio').click()
    })
})